Traceback (most recent call last):
  File "snippet.py", line 20, in <module>
    from tastypie.authentication import Authentication
  File "/usr/local/lib/python2.7/site-packages/tastypie/authentication.py", line 17, in <module>
    from tastypie.compat import (
  File "/usr/local/lib/python2.7/site-packages/tastypie/compat.py", line 13, in <module>
    AUTH_USER_MODEL = settings.AUTH_USER_MODEL
  File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 39, in _setup
    % (desc, ENVIRONMENT_VARIABLE))
django.core.exceptions.ImproperlyConfigured: Requested setting AUTH_USER_MODEL, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
