Traceback (most recent call last):
  File "snippet.py", line 68, in <module>
    main()
  File "snippet.py", line 49, in main
    con = connect()
  File "snippet.py", line 11, in connect
    con = MySQLdb.connect(host='localhost', db='test', user='testuser', passwd='password')
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/__init__.py", line 84, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 179, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (2002, "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)")

